#!/bin/sh

# Only suspend when not on power.
# TODO: Detect if we're on a battery for this.
if acpi | grep -q Discharging; then
    echo "suspending" > /tmp/susp
    /usr/bin/systemctl suspend
else
    echo 'not suspending' > /tmp/susp
    exit 0
fi
