#!/bin/sh

# Only suspend when not on power.
# TODO: Detect if we're on a battery for this.
if acpi | grep -q Discharging; then
    echo "suspending" > /tmp/susp
    /usr/bin/systemctl suspend
fi

if acpi 2>&1 | grep -q 'No support'; then
    /usr/bin/systemctl suspend
fi

